-- DB-02: Fix Receipt.studentId cascade behavior (SetNull on student deletion)
-- DB-03: Fix ReceiptItem.ledgerEntryId cascade behavior (Restrict deletion)
-- DB-04: Enforce Receipt.status as a proper database enum
-- DB-05: Enforce Class.status as a proper database enum
--
-- ALL CHANGES ARE SAFE FOR PRODUCTION DATA:
--   • Enum conversions use USING clause to cast existing valid string values.
--   • No data is deleted. No column values are changed.
--   • FK constraint additions/changes are done with ALTER TABLE.
--   • The USING cast will FAIL if any row contains an unexpected string value
--     (e.g. a typo like "active" or "REVERTED"). Run the audit queries below
--     first to verify data cleanliness before applying.
--
-- ── Pre-migration data audit (run these SELECT queries first) ─────────────────
-- Check for unexpected Receipt.status values (only "ACTIVE" or "REVERSED" allowed):
--   SELECT DISTINCT status FROM "Receipt";
--   Expected output: rows containing only 'ACTIVE' and/or 'REVERSED'
--
-- Check for unexpected Class.status values (only "ACTIVE" or "ARCHIVED" allowed):
--   SELECT DISTINCT status FROM "Class";
--   Expected output: rows containing only 'ACTIVE' and/or 'ARCHIVED'
-- ─────────────────────────────────────────────────────────────────────────────

BEGIN;

-- ── DB-05: Class.status String → ClassStatus enum ─────────────────────────────

-- 1. Create the PostgreSQL enum type
CREATE TYPE "ClassStatus" AS ENUM ('ACTIVE', 'ARCHIVED');

-- 2. Alter the column: cast existing string values to the new enum type
--    The USING expression converts the text value to the enum directly.
--    If any row has an unexpected value this statement will error (safe fail).
ALTER TABLE "Class"
    ALTER COLUMN "status" TYPE "ClassStatus"
    USING "status"::"ClassStatus";

-- 3. Set default to the enum value (not the string)
ALTER TABLE "Class"
    ALTER COLUMN "status" SET DEFAULT 'ACTIVE'::"ClassStatus";


-- ── DB-04: Receipt.status String → ReceiptStatus enum ────────────────────────

-- 1. Create the PostgreSQL enum type
CREATE TYPE "ReceiptStatus" AS ENUM ('ACTIVE', 'REVERSED');

-- 2. Alter the column: cast existing string values to the new enum type
ALTER TABLE "Receipt"
    ALTER COLUMN "status" TYPE "ReceiptStatus"
    USING "status"::"ReceiptStatus";

-- 3. Set default to the enum value
ALTER TABLE "Receipt"
    ALTER COLUMN "status" SET DEFAULT 'ACTIVE'::"ReceiptStatus";


-- ── DB-02: Receipt.studentId — add onDelete: SetNull FK constraint ────────────
-- The existing FK has no referential action (defaults to RESTRICT in PostgreSQL).
-- We need to DROP the old constraint and ADD a new one with ON DELETE SET NULL.
--
-- Find the current constraint name first (it was auto-generated by Prisma):
--   SELECT conname FROM pg_constraint
--   WHERE conrelid = '"Receipt"'::regclass AND contype = 'f'
--   AND conkey @> ARRAY[(SELECT attnum FROM pg_attribute
--                         WHERE attrelid = '"Receipt"'::regclass
--                         AND attname = 'studentId')::int2];
--
-- Prisma typically names this "Receipt_studentId_fkey". Drop and recreate:

ALTER TABLE "Receipt"
    DROP CONSTRAINT IF EXISTS "Receipt_studentId_fkey";

ALTER TABLE "Receipt"
    ADD CONSTRAINT "Receipt_studentId_fkey"
    FOREIGN KEY ("studentId")
    REFERENCES "Student"("id")
    ON DELETE SET NULL
    ON UPDATE CASCADE;


-- ── DB-03: ReceiptItem.ledgerEntryId — add onDelete: Restrict FK ─────────────
-- The existing FK has no explicit action (PostgreSQL default is RESTRICT, so
-- this is effectively already the correct behaviour). Making it explicit in the
-- schema ensures Prisma generates the correct migration in future schema diffs
-- and makes the intent clear in DB metadata.
--
-- Drop the implicit constraint and recreate it with an explicit RESTRICT clause.

ALTER TABLE "ReceiptItem"
    DROP CONSTRAINT IF EXISTS "ReceiptItem_ledgerEntryId_fkey";

ALTER TABLE "ReceiptItem"
    ADD CONSTRAINT "ReceiptItem_ledgerEntryId_fkey"
    FOREIGN KEY ("ledgerEntryId")
    REFERENCES "LedgerEntry"("id")
    ON DELETE RESTRICT
    ON UPDATE CASCADE;


COMMIT;

-- ── Post-migration verification ───────────────────────────────────────────────
-- 1. Verify Class.status type is now the enum:
--    SELECT data_type, udt_name FROM information_schema.columns
--    WHERE table_name = 'Class' AND column_name = 'status';
--    Expected: data_type = 'USER-DEFINED', udt_name = 'ClassStatus'
--
-- 2. Verify Receipt.status type is now the enum:
--    SELECT data_type, udt_name FROM information_schema.columns
--    WHERE table_name = 'Receipt' AND column_name = 'status';
--    Expected: data_type = 'USER-DEFINED', udt_name = 'ReceiptStatus'
--
-- 3. Verify Receipt.studentId FK has ON DELETE SET NULL:
--    SELECT conname, confdeltype FROM pg_constraint
--    WHERE conrelid = '"Receipt"'::regclass AND conname = 'Receipt_studentId_fkey';
--    Expected: confdeltype = 'n' (SET NULL)
--
-- 4. Verify ReceiptItem.ledgerEntryId FK has ON DELETE RESTRICT:
--    SELECT conname, confdeltype FROM pg_constraint
--    WHERE conrelid = '"ReceiptItem"'::regclass AND conname = 'ReceiptItem_ledgerEntryId_fkey';
--    Expected: confdeltype = 'r' (RESTRICT)
